AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    whats-at-abes

    Parses the Honest Abe's website creates a site with just the menu.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 20


Resources:

    PageRendererFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: page_renderer/
            Handler: app.lambda_handler
            Runtime: python3.7
            Policies:
            - AWSXrayWriteOnlyAccess
            - Statement:
              - Sid: AllowDynamoAccess
                Effect: Allow
                Action:
                    - dynamodb:Scan
                Resource: 'arn:aws:dynamodb:us-east-1:774656682386:table/WhatsAt-master3'
            - Statement:
              - Sid: AllowS3Access
                Effect: Allow
                Action:
                    - s3:Put*
                Resource: arn:aws:s3:::whatsatabes.com/*

    PageScraperFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: web_scraper/
            Handler: app.lambda_handler
            Runtime: python3.7
            Policies:
            - AWSXrayWriteOnlyAccess
            - Statement:
              - Sid: AllowDynamoAccess
                Effect: Allow
                Action:
                    - dynamodb:Put
                    - dynamodb:BatchWriteItem
                Resource: 'arn:aws:dynamodb:us-east-1:774656682386:table/WhatsAt-master3'

Outputs:

    PageRendererFunction:
      Description: "Web Scraper Lambda Function ARN"
      Value: !GetAtt PageRendererFunction.Arn
